---
openapi: 3.0.0
info:
  title: EndoSkullAPI doc
  description: "yes"
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/EndoSkull/Api-Doc/1.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
